openapi: 3.0.0
info:
  title: Durok Server
  version: v1
servers:
  - url: http://localhost:8080
paths:
  /version:
    get:
      summary: getVersion
      operationId: getVersion
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
  /devEntrypoint:
    get:
      summary: devEntrypoint
      operationId: devEntrypoint
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DevEntrypoint'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    VersionResponse:
      type: object
      properties:
        version:
          type: string
    DevEntrypoint:
      type: object
      properties:
        output:
          type: string
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string